### ISSUE TITLE
Slack has the same problem.

### ISSUE THREAD

**Issue by danielquinn** [paoloantinori/markdown_to_jira#2]
I love this idea.  Jira's Markdown plugin was abandoned years ago and I've been looking for just something like this so thank you for your hard work!

I actually found this plugin while searching for `slack markdown` strangely as Slack has the same problem: they have a kooky Slack-only format.  Come to think of it, so does Google+.  Perhaps it might make sense to break out the "translators" into site-specific flavours?

**Comment by paoloantinori** [comment]
Hi @danielquinn there is actually another project with that aim, called Marksy: https://chrome.google.com/webstore/detail/marksy/glncdocnokppgopgpblpeohhhcjggbnl?hl=en

I've probably never really used it since my main browser is Firefox and I have put together Chrome extension just for my colleagues.


(I didn't even know that Slack had a wiki. I only use it for chat where it already supports Markdown)


I don't really have the aim to turn this extension into something more generic, since I have put it together just to fix a personal nuance but if you decide to do so I'll be happy to point people to your implementation!
