### ISSUE TITLE
Firefox extension not compatible with Firefox Quantum

### ISSUE THREAD

**Issue by Lubits** [paoloantinori/markdown_to_jira#5]
The Firefox extension is no longer supported in the new Firefox versions. Beginning from Firefox 57, the browser switch to WebExtension addons.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions

Any plans on updating the Firefox extension to make it compatible with Firefox Quantum?

**Comment by paoloantinori** [comment]
hi there. yes, I'm going to look into this since I'd expect it's just a packaging or descriptor issue. I'll update here when I have something

**Comment by Lubits** [comment]
I think the issue will be more time consuming than that. It needs to be migrated from jpm to WebExtension.

According to Mozilla:
> Add-ons using the techniques described in this document are considered a legacy technology in Firefox. Don't use these techniques to develop new add-ons. Use WebExtensions instead. If you maintain an add-on which uses the techniques described here, consider migrating it to use WebExtensions.

https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Add-on_SDK/Tools/jpm

**Comment by blimmer** [comment]
I'm working on this on [a branch](https://github.com/blimmer/markdown_to_jira/tree/feature/webext) on my fork. Because Firefox Quantum uses WebExtension protocol, I'm totally refactoring the layout of this project to just be one codebase with multiple build targets (using webpack).

I'm about more than halfway done as it stands now and will make some time to work on this again in the next few weeks.

**Comment by paoloantinori** [comment]
Hi! Thank you! I won't be able to really dedicate time earlier than
Christmas I'm afraid!

**Comment by blimmer** [comment]
This issue can get closed out now - https://addons.mozilla.org/en-US/firefox/addon/markdown-to-jira/
